# Generated by Django 2.1.5 on 2019-02-07 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
                ('oName', models.CharField(max_length=15)),
                ('phoneNumber', models.IntegerField()),
                ('homeAddress', models.TextField(max_length=200)),
                ('busName', models.CharField(max_length=50)),
                ('busAddress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=100, unique=True)),
                ('phoneNumber', models.IntegerField()),
                ('contactMail', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=500)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplus.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=100, unique=True)),
                ('sortCode', models.IntegerField()),
                ('swiftCode', models.TextField()),
                ('contactAddress', models.CharField(max_length=200)),
                ('bank', models.ManyToManyField(to='iplus.Bank')),
                ('loanManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=500)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplus.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='LoanCritereia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=200)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplus.Bank')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplus.Category'),
        ),
    ]
