# Generated by Django 2.1.5 on 2019-02-12 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iplus', '0003_auto_20190212_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
